# Generated by Django 3.1.1 on 2021-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='find_photos')),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('find_images', models.ManyToManyField(blank=True, related_name='group', to='find_photo.Images')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
