# Generated by Django 3.1.1 on 2021-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_photo', '0003_auto_20210411_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedIndexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
