# Generated by Django 3.1.1 on 2021-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_photo', '0004_auto_20210411_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='index',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
