# Generated by Django 3.1.1 on 2021-04-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_photo', '0005_auto_20210411_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['index'], 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='groups',
            name='description',
        ),
    ]
