# Generated by Django 3.1.1 on 2021-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_photo', '0007_auto_20210411_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='find_images'),
        ),
    ]
