# Generated by Django 3.1.1 on 2021-04-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_photo', '0008_auto_20210412_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
